INSERT INTO TABLES (ID, TABLE_NAME, NO_OF_PEOPLE) VALUES (1, 'Masa 1', 1);
INSERT INTO TABLES (ID, TABLE_NAME, NO_OF_PEOPLE) VALUES (2, 'Masa 2', 1);
INSERT INTO TABLES (ID, TABLE_NAME, NO_OF_PEOPLE) VALUES (3, 'Masa 3', 3);
INSERT INTO TABLES (ID, TABLE_NAME, NO_OF_PEOPLE) VALUES (4, 'Masa 4', 3);
INSERT INTO TABLES (ID, TABLE_NAME, NO_OF_PEOPLE) VALUES (5, 'Masa 5', 9);
INSERT INTO TABLES (ID, TABLE_NAME, NO_OF_PEOPLE) VALUES (6, 'Masa 6', 10);

INSERT INTO SCHEDULE_DAY(ID, WEEK_DAY, START, END ) VALUES (1, "MONDAY", 8, 22);
INSERT INTO SCHEDULE_DAY(ID, WEEK_DAY, START, END ) VALUES (2, "TUESDAY", 8, 22);
INSERT INTO SCHEDULE_DAY(ID, WEEK_DAY, START, END ) VALUES (3, "WEDNESDAY", 8, 22);
INSERT INTO SCHEDULE_DAY(ID, WEEK_DAY, START, END ) VALUES (4, "THURSDAY", 8, 22);
INSERT INTO SCHEDULE_DAY(ID, WEEK_DAY, START, END ) VALUES (5, "FRIDAY", 8, 22);
INSERT INTO SCHEDULE_DAY(ID, WEEK_DAY, START, END ) VALUES (6, "SUNDAY", 8, 20);
INSERT INTO SCHEDULE_DAY(ID, WEEK_DAY, START, END ) VALUES (7, "SATURNDAY", 8, 18);
